---
- name: CIS 4.4.3.3.1 - Ensure password history is enforced (pam_unix.so remember=5)
  hosts: all
  become: true
  gather_facts: true

  vars:
    control_id: "4.4.3.3.1"
    control_name: "Ensure password history is enforced (remember=5)"
    remember_val: 5
    cis_enforce: true   # ค่าเริ่มต้น audit-only; จะให้แก้จริงใส่ -e "cis_enforce=true"

  tasks:
    - name: Detect current login user
      debug:
        msg: "Login as: {{ ansible_user_id }}, Become: {{ ansible_effective_user_id | default('root') }}"

    - name: Guard | Oracle Linux 8 family only
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] == "RedHat"
          - ansible_facts['distribution'] in ["OracleLinux", "RedHat", "Rocky", "AlmaLinux"]
          - (ansible_facts['distribution_major_version'] | int) == 8
        fail_msg: "Unsupported OS. Expect OracleLinux 8.x family."

    # ---------- AUDIT ----------
    - name: Audit | Read current pam_unix.so remember value from system-auth
      ansible.builtin.shell: |
        set -o pipefail
        if [ -f /etc/pam.d/system-auth ]; then
          grep -E '^password[[:space:]]+sufficient[[:space:]]+pam_unix\.so.*remember=' /etc/pam.d/system-auth || true
        fi
      args: { executable: /bin/bash }
      register: remember_current
      changed_when: false
      failed_when: false

    # ---------- ENFORCE (optional) ----------
    - name: Enforce | Ensure remember value in pam_unix.so line (system-auth)
      when: cis_enforce | bool
      ansible.builtin.replace:
        path: /etc/pam.d/system-auth
        regexp: '^password\s+sufficient\s+pam_unix\.so.*'
        replace: 'password    sufficient    pam_unix.so remember={{ remember_val }} use_authtok sha512 shadow'
        backup: true

    # ---------- VERIFY ----------
    - name: Verify | pam_unix.so remember equals expected
      ansible.builtin.shell: |
        set -o pipefail
        if [ -f /etc/pam.d/system-auth ]; then
          grep -E '^password[[:space:]]+sufficient[[:space:]]+pam_unix\.so.*remember={{ remember_val }}' /etc/pam.d/system-auth || true
        fi
      args: { executable: /bin/bash }
      register: remember_verify
      changed_when: false
      failed_when: false

    # ---------- RESULT ----------
    - name: Build result for CSV export
      set_fact:
        new_result:
          control_id: "{{ control_id }}"
          name: "{{ control_name }}"
          command: "system-auth -> pam_unix.so remember={{ remember_val }}"
          expected: "pam_unix.so line contains remember={{ remember_val }}"
          result: >-
            current={{ remember_current.stdout | default('') | trim }}; 
            verify_line={{ (remember_verify.stdout | default('Not Found')) | regex_replace('\n',' ') }};
          status: "{{ 'Pass' if (remember_verify.stdout | default('') | length > 0) else 'Fail' }}"
          host: "{{ inventory_hostname }}"
          ip: "{{ ansible_host | default(ansible_default_ipv4.address | default('N/A')) }}"

    - name: Append result to result_list
      set_fact:
        result_list: "{{ result_list | default([]) + [ new_result ] }}"

    - name: Add host result list to reporting group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: cis_report
        result_list: "{{ result_list }}"

# ===== CSV Reporting =====
- name: Export CIS 4.4.3.3.1 Results to CSV
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Combine result_list from all hosts
      set_fact:
        combined_results: >-
          {{
            hostvars.values()
            | selectattr('result_list', 'defined')
            | map(attribute='result_list')
            | list
            | flatten
          }}

    - name: Export combined result list to CSV (Local)
      copy:
        content: |
          control_id,cis_name,command,expected_result,actual_result,host,ip,status
          {% for r in combined_results -%}
          "{{ r.control_id }}","{{ r.name }}","{{ r.command }}","{{ r.expected }}","{{ (r.result | replace('\n',' ') | replace(',', ';') ) }}","{{ r.host }}","{{ r.ip }}","{{ r.status }}"
          {% endfor %}
        dest: "./cis_4_4_3_3_1_report.csv"
