---
- name: CIS 3.3.9 - Enable logging of suspicious packets (log_martians)
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: 3.3.9 - Enable logging suspicious packets (all)
      ansible.builtin.sysctl:
        name: net.ipv4.conf.all.log_martians
        value: '1'
        sysctl_set: yes
        reload: yes
        sysctl_file: /etc/sysctl.d/99-network.conf
      register: log_martians_all
      when: ansible_system == 'Linux'

    - name: 3.3.9 - Enable logging suspicious packets (default)
      ansible.builtin.sysctl:
        name: net.ipv4.conf.default.log_martians
        value: '1'
        sysctl_set: yes
        reload: yes
        sysctl_file: /etc/sysctl.d/99-network.conf
      register: log_martians_default
      when: ansible_system == 'Linux'

    - name: 3.3.9 - Build result for CSV export
      set_fact:
        new_result:
          control_id: "3.3.9"
          name: "Enable logging of suspicious packets (log_martians)"
          command: "sysctl net.ipv4.conf.all/default.log_martians = 1"
          expected: "Both values should be set to 1"
          result: "all={{ log_martians_all.msg | default('N/A') }}, default={{ log_martians_default.msg | default('N/A') }}"
          status: "{{ 'Pass' if not log_martians_all.failed and not log_martians_default.failed else 'Fail' }}"
          host: "{{ inventory_hostname }}"
          ip: "{{ ansible_host | default(ansible_default_ipv4.address | default('N/A')) }}"

    - name: 3.3.9 - Append result to result_list
      set_fact:
        result_list: "{{ result_list | default([]) + [ new_result ] }}"

- name: Export CIS 3.3.9 Results to CSV
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Combine result_list from all hosts
      set_fact:
        combined_results: >-
          {{
            hostvars.values()
            | selectattr('result_list', 'defined')
            | map(attribute='result_list')
            | list
            | flatten
          }}

    - name: Export combined result list to CSV (Local)
      copy:
        content: |
          control_id,cis_name,command,expected_result,actual_result,host,ip,status
          {% for r in combined_results %}
          "{{ r.control_id }}","{{ r.name }}","{{ r.command }}","{{ r.expected }}","{{ r.result | default('') | replace('\n',' ') | trim | replace(',',';') }}","{{ r.host }}","{{ r.ip }}","{{ r.status | trim }}"
          {% endfor %}
        dest: "./cis_3_3_9_report.csv"
