---
- name: CIS 4.4.3.2.7 - Ensure password quality policy is enforced for root user (pam_pwquality retry=3)
  hosts: all
  become: true
  gather_facts: true

  vars:
    control_id: "4.4.3.2.7"
    control_name: "Ensure password quality policy is enforced for root user"
    retry_val: 3
    cis_enforce: true   # ค่าเริ่มต้น audit-only; จะให้แก้จริงใส่ -e "cis_enforce=true"

  tasks:
    - name: Detect current login user
      debug:
        msg: "Login as: {{ ansible_user_id }}, Become: {{ ansible_effective_user_id | default('root') }}"

    - name: Guard | Oracle Linux 8 family only
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] == "RedHat"
          - ansible_facts['distribution'] in ["OracleLinux", "RedHat", "Rocky", "AlmaLinux"]
          - (ansible_facts['distribution_major_version'] | int) == 8
        fail_msg: "Unsupported OS. Expect OracleLinux 8.x family."

    # ---------- AUDIT ----------
    - name: Audit | Read current pam_pwquality retry value
      ansible.builtin.shell: |
        set -o pipefail
        if [ -f /etc/pam.d/system-auth ]; then
          grep -E '^password[[:space:]]+requisite[[:space:]]+pam_pwquality\.so.*retry=' /etc/pam.d/system-auth || true
        fi
      args: { executable: /bin/bash }
      register: retry_current
      changed_when: false
      failed_when: false

    # ---------- ENFORCE (optional) ----------
    - name: Enforce | Ensure retry value in pam_pwquality.so line
      when: cis_enforce | bool
      ansible.builtin.replace:
        path: /etc/pam.d/system-auth
        regexp: '^password\s+requisite\s+pam_pwquality\.so.*'
        replace: 'password    requisite    pam_pwquality.so retry={{ retry_val }}'
        backup: true

    # ---------- VERIFY ----------
    - name: Verify | pam_pwquality retry equals expected
      ansible.builtin.shell: |
        set -o pipefail
        if [ -f /etc/pam.d/system-auth ]; then
          grep -E '^password[[:space:]]+requisite[[:space:]]+pam_pwquality\.so[[:space:]]+retry={{ retry_val }}' /etc/pam.d/system-auth || true
        fi
      args: { executable: /bin/bash }
      register: retry_verify
      changed_when: false
      failed_when: false

    # ---------- RESULT ----------
    - name: Build result for CSV export
      set_fact:
        new_result:
          control_id: "{{ control_id }}"
          name: "{{ control_name }}"
          command: "system-auth -> pam_pwquality.so retry={{ retry_val }}"
          expected: "pam_pwquality.so line contains retry={{ retry_val }}"
          result: >-
            current={{ retry_current.stdout | default('') | trim }};
            verify_line={{ (retry_verify.stdout | default('Not Found')) | regex_replace('\n',' ') }};
          status: "{{ 'Pass' if (retry_verify.stdout | default('') | length > 0) else 'Fail' }}"
          host: "{{ inventory_hostname }}"
          ip: "{{ ansible_host | default(ansible_default_ipv4.address | default('N/A')) }}"

    - name: Append result to result_list
      set_fact:
        result_list: "{{ result_list | default([]) + [ new_result ] }}"

    - name: Add host result list to reporting group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: cis_report
        result_list: "{{ result_list }}"

# ===== CSV Reporting =====
- name: Export CIS 4.4.3.2.7 Results to CSV
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Combine result_list from all hosts
      set_fact:
        combined_results: >-
          {{
            hostvars.values()
            | selectattr('result_list', 'defined')
            | map(attribute='result_list')
            | list
            | flatten
          }}

    - name: Export combined result list to CSV (Local)
      copy:
        content: |
          control_id,cis_name,command,expected_result,actual_result,host,ip,status
          {% for r in combined_results %}
          "{{ r.control_id }}","{{ r.name }}","{{ r.command }}","{{ r.expected }}","{{ r.result | replace(',', ';') }}","{{ r.host }}","{{ r.ip }}","{{ r.status }}"
          {% endfor %}
        dest: "./cis_4_4_3_2_7_report.csv"
